### ISSUE TITLE
Hi! Can you please add a license to the pure go version :)

### ISSUE THREAD

**Issue by ghost** [keybase/go-tweetnacl#1]
Hi! Can you please add a license to the pure go version? Specifically this file:
https://github.com/keybase/go-tweetnacl/blob/master/go/tweetnacl.go 
Thanks 😃

**Comment by maxtaco** [comment]
I don't recommend using this implementation.  It's half-baked and likely way slower than the official Go implementation!

**Comment by ghost** [comment]
That's fair - I have a specific use case / extension where I would prefer to have golang's memory safety for which I have ported over some of the original c code from cr.yp.to to golang. For auditability reasons, it will look quite similar, to the original c code, and thus to this. (Though I think there are some small differences, I haven't checked closely yet). It will be hosted at http://github.com/mooti-dev/RingCT once I finish it. Let me know if you have any concerns.

**Comment by maxtaco** [comment]
No concerns, just caveat emptor.  I'll slap a license on it, give me one second.

**Comment by ghost** [comment]
Ok thank you.
